# Nome do Workflow
name: DevOpsLab Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configurando o python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'

      - name: Instalando requisitos
        run:  pip install flask
              
      - name: Executando testes unitários
        run: python -m unittest -v test